CREATE TABLE IF NOT EXISTS "Companies" (
    "Id" UUID PRIMARY KEY,
    "Name" TEXT NOT NULL UNIQUE,
    "Website" TEXT,
    "Location" TEXT,
    "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "Jobs" (
    "Id" UUID PRIMARY KEY,
    "CompanyId" UUID NOT NULL REFERENCES "Companies" ("Id") ON DELETE CASCADE,
    "Title" TEXT NOT NULL,
    "Location" TEXT,
    "SalaryMin" NUMERIC,
    "SalaryMax" NUMERIC,
    "Description" TEXT,
    "Source" TEXT NOT NULL,
    "ExternalId" TEXT NOT NULL,
    "DatePosted" DATE,
    "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE ("Source", "ExternalId")
);

CREATE TABLE IF NOT EXISTS "Technologies" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" TEXT NOT NULL UNIQUE,
    "Category" TEXT,
    "CreatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "JobTechnologies" (
    "JobId" UUID NOT NULL REFERENCES "Jobs" ("Id") ON DELETE CASCADE,
    "TechnologyId" BIGINT NOT NULL REFERENCES "Technologies" ("Id") ON DELETE CASCADE,
    "ConfidenceScore" NUMERIC,
    PRIMARY KEY ("JobId", "TechnologyId")
);
